name: Package and Release Magisk Module

on:
    workflow_dispatch:
        inputs:
            release_type:
                description: 'Release Type'
                required: true
                default: 'latest'
                type: choice
                options:
                    - latest
                    - prerelease

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            - name: Read module info
                id: module_info
                run: |
                    VERSION=$(grep "version=" module.prop | cut -d= -f2)
                    VERSION_CODE=$(grep "versionCode=" module.prop | cut -d= -f2)
                    echo "version=$VERSION" >> $GITHUB_OUTPUT
                    echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT

            - name: Generate changelog
                id: changelog
                run: |
                    CHANGELOG=$(git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 2>/dev/null || echo HEAD~10)..HEAD)
                    echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
                    echo "$CHANGELOG" >> $GITHUB_OUTPUT
                    echo "EOF" >> $GITHUB_OUTPUT

            - name: Create ZIP package
                run: |
                    zip -r magisk-module.zip * -x ".git/*" ".github/*" "README.md" "LICENSE"

            - name: Create Release
                uses: softprops/action-gh-release@v1
                with:
                    tag_name: v${{ steps.module_info.outputs.version }}
                    name: Release v${{ steps.module_info.outputs.version }} (Build ${{ steps.module_info.outputs.version_code }})
                    body: ${{ steps.changelog.outputs.CHANGELOG }}
                    files: magisk-module.zip
                    prerelease: ${{ github.event.inputs.release_type == 'prerelease' }}
                    draft: false
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
